### ISSUE TITLE
Support different log file encodings

### ISSUE THREAD

**Issue by targodan** [targodan/UberSpatchBoard#19]
# Bugreport

- Operating system and version: Windows 7
- UberSpatchBoard version: bleeding edge
- Java version: 1.8

## What did you expect to happen?

Unicode characters to be displayed correctly.

## What did actually happen?

Broken unicode.

## Consequence

Support different encodings for different log files. Maybe even add a auto-detection feature.

**Comment by Holladiewal** [comment]
Pointer?: https://github.com/ThisIsJustAnotherOrganization/JAFRDB/blob/master/src/LogHandler.kt#L47
