### ISSUE TITLE
Test irc formatting

### ISSUE THREAD

**Issue by targodan** [targodan/UberSpatchBoard#20]
Test if IRC formatting (especially in RATSIGNALS) might cause problems. Hexchat doesn't log them but other clients might.

Maybe make this a task for the marshaller implementations.

Example with formatting: https://gist.github.com/targodan/fdf5ec51d37057432bd1a32ae794c796

**Comment by targodan** [comment]
Parsing ratsignal doesn't work.

Related article about querying if a char is printable: https://stackoverflow.com/questions/220547/printable-char-in-java

**Comment by Holladiewal** [comment]
Pointer: https://github.com/ThisIsJustAnotherOrganization/JAFRDB/blob/master/src/Stuff.kt#L25
